### ISSUE TITLE
Ion Identity Network as alternative/complement to CliqueMS

### ISSUE THREAD

**Issue by Adafede** [zamboni-lab/SLAW#12]
Hi @adelabriere,

Have you tried the [Ion Identity Networking](https://doi.org/10.1038/s41467-021-23953-9) workflow in comparison to CliqueMS' one?

One of the advantages (also linked to #9) is that it directly writes the info in the needed format in the MGF export.

Best,

**Comment by adelabriere** [comment]
Hi @Adafede,

You are right it is probably better. And I don't really like the cliqueMS solution but it was better than CAMERA and RAMClust. I ll have a look at it.
