### ISSUE TITLE
Assignment between MS1 and MS2 data

### ISSUE THREAD

**Issue by chufz** [zamboni-lab/SLAW#16]
Dear Alexis,

So as far as I understand my SLAW- output, the ms1 data matrices contain the `ms id` column that refers in the fused mgf file to the number of the scan entry. Can you confirm?

@michaelwitting and I are trying to align a spectral library search output to the data matrices, however, it involves a bit of data-wrangling.

I am still wondering in the fused mgf file, the FEATURE= variable, how this refers to the ms1 data, and from which data matrix (reduced, non_reduced)? 
Is there an easier way for this alignment job?

Thanks in advance for your help.

**Comment by adelabriere** [comment]
Dear @chufz , I am sorry for the delay,

The `ms2_id` refers the the position of the spectrum in the mgf file yes. Example, 1_(e30)|2_(e50) means that for this feature there is two associated MS-MS one with a collision energy of 30, the first spectrum in the mgf from top to bottom and one with a collision energy of 50 the second spectrum from top to bottom. 

FEATURE=SOMENUMBER gives the row number in the raw datamatrix (datamatrix_******). 

So normally if you have spectral match results and you have their position in the MGF, you can just look back at the FEATURE tag in the matrix and find the corresponding row of the data matrix. You can also just look for the corresponding position in the `ms2_id`.

**Comment by michaelwitting** [comment]
Thanks! That is exactly what we thought. We have now some R code performing the mapping for us.
