### ISSUE TITLE
Output tables

### ISSUE THREAD

**Issue by dwalke04** [zamboni-lab/SLAW#2]
Hello,
Thanks for your excellent work on this software. There seems to be a minor error with the output formatting. After running the example data files, the output file extension was .csv, yet the files were actually tab delimited. Thanks!

**Comment by adelabriere** [comment]
Hi @dwalke04. Thanks for the feedback, this actually intended as if you are on windows as a lot of the biologists I work with are, you can open a .csv directly in Excel and not a .tsv. If this really bug people I'll change it so I am letting this issue opened at the moment.

**Comment by dwalke04** [comment]
Thank you. You may want to confirm the output is correct. When I try to open the file on a Mac or Windows, it still did not recognize the delimiters (see below). To get this to work, I either had to rename the extension or input through excel, which may be difficult for some users. Either way, everything else works great!

![image](https://user-images.githubusercontent.com/10214437/141166176-b3d23c9c-d227-44db-8779-423e46a23bfb.png)

**Comment by htmonkey** [comment]
This is a common issue with Excel when dealing with txt files. You can either use "Convert Text to Column" function in Excel, or "Get Data from File", or drag-and-drop the csv file obtained from SLAW into a empty Excel worksheet.
