### ISSUE TITLE
Are there specific processes of the blank sample?

### ISSUE THREAD

**Issue by YUANMY2021** [zamboni-lab/SLAW#20]
Recently, when I am checking my results of Slaw-processed 400 samples

    I noticed that I included the blank group in the sample group information CSV file （Figure 1)
![image](https://user-images.githubusercontent.com/79961133/195494964-3658e81b-4219-4f92-a6b1-df3f79a094a1.png)

    But the output file still contains the intensity data of the blank sample.

    But the README said "Blanks will be discarded from the final peaktable."
 I am wondering the anything was done to the Blank sample during the data processing 
or do I need to do the blank-sample-feature-filter step after using Slaw? Thanks

**Comment by htmonkey** [comment]
Peaks from blanks are discarded after alignment when SLAW decides what features should be considered for the peak master table that combines all peaks across all samples (but blanks). However, the peaks that are retained (on the basis of non-blank samples) are also reported and gap-filled for blanks. 

This allows to calculate sample/blank ratios and exclude features in downstream processing.
