### ISSUE TITLE
Incorrect assignment of processes on CPU cores

### ISSUE THREAD

**Issue by chufz** [zamboni-lab/SLAW#24]
![screenshot-alacritty-2022-12-01-10-11-55](https://user-images.githubusercontent.com/38219063/205047232-f1e37555-3ea0-4178-90dc-8946429941b4.png)
Hi,

I am using the current version of slaw on an HPC cluster (os7) using a singularity container. I am truncating the memory and cores to the applied resources of the job submit by:

```SINGULARITYENV_NCORES=8 SINGULARITYENV_MEMORY=4000 singularity run ```

The output file then states the correct assignment of parameters:

``` Total memory available: 435561 and 56 cores. The workflow will use 4000 Mb by core on 8 cores.```
However, I observed that on the nodes more processes were spawned, see attached screenshot. Also, only one of these processes was actually running, the others were blocked on waiting.

I just briefly went through the code and I am wondering if the 'NUM_CORES' variable in the Rscripts (like fusing_msms_spectra.R) are assigned correctly?

Thanks a lot for your help

![](imap://huberc@imap.ufz.de:143/fetch%3EUID%3E/INBOX%3E16713?part=1.2&type=image/png&filename=screenshot-alacritty-2022-12-01-10-11-55.png)

**Comment by htmonkey** [comment]
which branch?

**Comment by chufz** [comment]
I was pulling from the Master branch
