### ISSUE TITLE
Docker on arm64 (Dockerfile for adelabriere/basis_workflow)

### ISSUE THREAD

**Issue by wolski** [zamboni-lab/SLAW#29]
I would like to have a docker image for arm64.

This seems to be possible given the Dockerfile `https://github.com/zamboni-lab/SLAW/blob/master/Dockerfile`
However, there is only `amd64` docker image `adelabriere/basis_workflow`.

Would it be please possible to share the Dockerfile for the  `adelabriere/basis_workflow` image?

**Comment by htmonkey** [comment]
I don't have it. Just start from scratch.
