### ISSUE TITLE
no data matrices or fused_mgf in output after run

### ISSUE THREAD

**Issue by RossetNina** [zamboni-lab/SLAW#30]
I ran SLAW with optimization on a samples set of around 250 .mzXML files. It produced all the optimization files in the output folder and then went on to process the dataset with the optimized parameters. It finished running without any errors but the output folders for datamatrices and fused_mgf were empty at the end of the run. Why did it not produce these results files?

**Comment by htmonkey** [comment]
Hard to say. You should rerun it with -e logging=DEBUG and paste the log.
