### ISSUE TITLE
Alignment step very slow for large datasets

### ISSUE THREAD

**Issue by YasinEl** [zamboni-lab/SLAW#31]
Hello and thank you for this tool. 
It seems that for large datasets (2.5k mzML files) using default settings the alignment steps seems to be very slow i.e. never finishes. I was wondering if there have been further developments on this? 

This was on a Windows11 PC.

Thank you,
Yasin

**Comment by htmonkey** [comment]
I would need examples/data to check. 
The performance should be similar to or better than what we reported in the Anal Chem paper with 2'500 QExactive data. If your run the docker with -e logging=DEBUG I can get a sense of what steps are taking longer in your case. You might also try the dev branch, which includes a couple of fixes.
