### ISSUE TITLE
Get different numbers of features(diff mz range of total mz range) with different running cores on singularity

### ISSUE THREAD

**Issue by YUANMY2021** [zamboni-lab/SLAW#8]
Sorry to trouble you again:
For in this way (try on slaw/msms), whether  I try how much cores, I couldn't get all of the features results as I got in (slaw/dev or slaw), The maximum's results  30cores only have half of my attempt on slaw_dev(although in slaw_dev can not export the fused_mgf)

The list below are my attempt:

**1.25cores** attempt on singularity running 
**1941108 features**
![image](https://user-images.githubusercontent.com/79961133/144732031-ec0db8ed-0a3c-47a6-8fb8-7e2b5f675f30.png)

2.30cores attempt on singularity running
**1960594 features**
![image](https://user-images.githubusercontent.com/79961133/144732052-b10df07a-bce4-459c-a27e-63e4b1589c9e.png)

3.35 cores attempt on singularity running
**1927792features**
![image](https://user-images.githubusercontent.com/79961133/144732062-25dafff3-ee50-4a88-92e7-13ee739025b4.png)

4.65 cores attempt on singularity running
**1012120features**
![image](https://user-images.githubusercontent.com/79961133/144732076-75ab4ae9-e983-4f67-a04e-cb492209f162.png)

5.143 cores attempt on singularity running
**75788features**
![image](https://user-images.githubusercontent.com/79961133/144732088-7c4802d6-0c87-4d5c-89dc-9c5ea2b42452.png)

**Comment by YUANMY2021** [comment]
Excuse me 
I also checked the overlap of these results 😞
Looks like here
But It seems that they all are not the whole features (for the mz range are different 100-700 or 100-1000,But actually it maybe 100-1400)
![image](https://user-images.githubusercontent.com/79961133/144817182-ffb85f72-f056-4813-8936-705aff73001e.png)

**Comment by htmonkey** [comment]
Some comments:
- I can't reproduce this. 
- It would be important to know what tolerance you use to quantify the overlap, and whether rerunning the optimization with the same number of cores provides better stability. If not. the issue doesn't depend on the number of cores.
- You are obtaining 2 Mio features. In my experience, it's an indicator that (i) you are picking noise, or (ii) your samples are veeeeery different, i.e. from unrelated batches.
I'll close for now. If the same issues shows up, it would be useful to have access to the data.
