### ISSUE TITLE
Missing MS1 data in mgf export

### ISSUE THREAD

**Issue by michaelwitting** [zamboni-lab/SLAW#9]
Hi,
I'm currently testing SLAW and so far it works well. However, I want to also export the MS1 isotope pattern in the mgf, but the respective option is not working. This is independent of the peak picking workflow.
Best regards,
Michael

**Comment by adelabriere** [comment]
Hi @michaelwitting It is not working yet. I am working on the feature but it is more complex than expected while keeping the scalability, as MS-MS fusion and raw isotopic pattern extraction are independent. I'll tag you here as soon as the option does its job.

**Comment by michaelwitting** [comment]
Thanks!

**Comment by michaelwitting** [comment]
Hi @adelabriere ,

just a short heads up: How is it going with the MS1 data export? @chufz and I wrote an R workflow for metabolite annotation taking the SLAW output and we would love to include the MS1 data, e.g. shuffeling things over to Sirius etc.

Best,

Michael

**Comment by htmonkey** [comment]
The new feature was implemented in the dev branch. Will need testing, but it's there.
